name: Link Checker

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Links in Markdown Files
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: 'pages/blog/posts/applicability-json-schema-fundamentals-part-1.md'
          retry: true
          urlRewriteSearch: '/o/'
          urlRewriteReplace: cra
          verbosity: DEBUG
