name: Trigger Update Landscape Tooling Workflow

on:
  push:
    paths:
      - data/tooling-data.yaml
  workflow_dispatch:


jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger update landscape repository workflow
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $PERSONAL_ACCESS_TOKEN" \
            https://api.github.com/repos/darhkvoyd/landscape/actions/workflows/update-landscape-tooling.yml/dispatches \
            -d '{"ref":"main"}'
