name: Trigger Update Landscape Tooling Workflow

on:
  push:
    paths:
      - data/tooling-data.yaml

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger update landscape repository workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/darhkvoyd/landscape/actions/workflows/update-landscape-tooling.yml/dispatches \
            -d '{"ref":"automate-landscape-tooling-data"}'
